### ISSUE TITLE
Pacote não instala

### ISSUE THREAD

**Issue by VictorLessa** [Rocketseat/adonis-bull#45]
npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path D:\Documents\3C\3c-perdas\node_modules\body-parser\node_modules\debug
npm ERR! dest D:\Documents\3C\3c-perdas\node_modules\body-parser\node_modules\.debug.DELETE
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, rename 'D:\Documents\3C\3c-perdas\node_modules\body-parser\node_modules\debug' -> 'D:\Documents\3C\3c-perdas\node_modules\body-parser\node_modules\.debug.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Victor\AppData\Roaming\npm-cache\_logs\2020-12-18T12_51_38_733Z-debug.log

Sempre que tento instalar o pacote aparece esse erro

**Comment by HigoRibeiro** [comment]
Victor, conseguiu instalar depois?
Pode ser algo relacionado a versão do node.

**Comment by jpedroschmitz** [comment]
Hey @VictorLessa, this issue was closed because it was not following the guidelines [described here](https://github.com/Rocketseat/adonis-bull/blob/master/.github/CONTRIBUTING.md#language).

While contributing or interacting in any way in this project, refrain from using any language other than English.
