### ISSUE TITLE
Como posso limpar a fila que contem a mesma mensagem

### ISSUE THREAD

**Issue by VictorLessa** [Rocketseat/adonis-bull#46]
Eu possuo uma tarefa onde construo uma estrutura JSON para gráfico que é ativada sempre que um cliente atualiza ou finaliza um serviço. Gostaria de, ao iniciar essa tarefa, verificar se existe a mesma tarefa em fila para apaga-las, já que o resultado será o mesmo que a tarefa que tinha acabado de finalizar

**Comment by fhugoduarte** [comment]
Hi @VictorLessa .

You first need to pass a jobId when adding your job to the queue, you can use the user id for that. So to remove, just use the remove method, like this:

```js
await Bull.remove("job-key", jobId);
```

You can put this code inside a try/catch so that if the job is no longer in the queue, it doesn't generate an exception.

**Comment by jpedroschmitz** [comment]
Hey @VictorLessa, I am going to close this issue because it is not following the guidelines [described here](https://github.com/Rocketseat/adonis-bull/blob/master/.github/CONTRIBUTING.md#language).

While contributing or interacting in any way in this project, refrain from using any language other than English.
