### ISSUE TITLE
queue.Job is not a constructor

### ISSUE THREAD

**Issue by fingunt** [Rocketseat/adonis-bull#48]
Ola estou testando, e esta tendo teste retorno no erro alguma dica

queue.Job is not a constructor
![Screen Shot 2021-01-18 at 12 06 31](https://user-images.githubusercontent.com/33792792/104931753-9c231780-5985-11eb-987d-7bada4afb473.png)

**Comment by HigoRibeiro** [comment]
Hey @fingunt !
I think you may have passed a wrong path in your `start/jobs` or there has some error in your implementation.

Can you look at these files or show me?

**Comment by fingunt** [comment]
![Uploading Screen Shot 2021-01-19 at 10.35.18.png…]()

**Comment by fingunt** [comment]
seria este
![Screen Shot 2021-01-19 at 10 35 18](https://user-images.githubusercontent.com/33792792/105041708-1618d680-5a42-11eb-8603-916afe4eaa14.png)

**Comment by fingunt** [comment]
outra 
![Screen Shot 2021-01-19 at 10 36 34](https://user-images.githubusercontent.com/33792792/105041811-38aaef80-5a42-11eb-9046-2a5a8c887c02.png)

**Comment by HigoRibeiro** [comment]
And the `UserRegisterEmail.js`?

**Comment by fingunt** [comment]
seria este
![Screen Shot 2021-01-19 at 11 34 28](https://user-images.githubusercontent.com/33792792/105048433-57ad7f80-5a4a-11eb-8f32-6e7649487a68.png)

**Comment by jpedroschmitz** [comment]
Hey @fingunt, I am going to close this issue because it is not following the guidelines [described here](https://github.com/Rocketseat/adonis-bull/blob/master/.github/CONTRIBUTING.md#language).

While contributing or interacting in any way in this project, refrain from using any language other than English.

If you still have questions, I recommend you open a new issue in English, this way our community can help you out 💜
