### ISSUE TITLE
Fila para após uns minutos

### ISSUE THREAD

**Issue by rodrigogaraujo** [Rocketseat/adonis-bull#49]
Tenho uma api onde preciso enviar notificações

Nessa api tem uma lista com notificaçoes a serem enviadas ao decorrer do dia.

As primeiras sempre vão tudo certinho

Mas após uma duas horas as outras notificações não são enviadas.

Alguém já passou por isso?

Adicionei try catch em todo passo para ver se dar algum erro, mas não tem erro algum

**Comment by ruanitto** [comment]
> Tenho uma api onde preciso enviar notificações
> 
> Nessa api tem uma lista com notificaçoes a serem enviadas ao decorrer do dia.
> 
> As primeiras sempre vão tudo certinho
> 
> Mas após uma duas horas as outras notificações não são enviadas.
> 
> Alguém já passou por isso?
> 
> Adicionei try catch em todo passo para ver se dar algum erro, mas não tem erro algum

Comigo aconteceu, mas com erros mesmo por conta de alguns métodos dentro da fila, identifiquei conectando no redis e vendo os Jobs com falha, cada tentantiva de execução que falha, o Job mantém a descrição do erro junto dos dados no redis

**Comment by jpedroschmitz** [comment]
Hey @rodrigogaraujo, I am going to close this issue because it is not following the guidelines [described here](https://github.com/Rocketseat/adonis-bull/blob/master/.github/CONTRIBUTING.md#language).

While contributing or interacting in any way in this project, refrain from using any language other than English.
